import Head from 'next/head'
import { getBackground, getHeaders, getLogo, getMenu } from '../lib/api'
import Navbar from '../components/Navbar/Navbar'
import Menu from '../components/Menu/Menu'
import { motion } from 'framer-motion'
import Footer from '../components/Footer/Footer'

export default function Home(props) {
  const headers = props.headers.data.headersCollection.items
  const logo = props.logo.data.logo
  const background = props.background.data.backgroundImage.background.url
  const menu = props.menu
  console.log(background)
  return (
    <div>
      <Head>
        <title>Charlees at home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/small-logo.png" />
      </Head>
      <Navbar logo={logo} />
      <main className='bg-gray-900'>
        <div className="hero min-h-screen" style={{ backgroundImage: `url(${background})` }}>
          <div className="hero-overlay bg-opacity-60"></div>
          <div className="hero-content text-center text-neutral-content">
            <div className="max-w-md text-white">
              <h1 className="mb-5 text-7xl font-bold">{headers[0].firstHeader}</h1>
              <p className="mb-5 text-2xl">{headers[0].description}</p>
              <motion.button
                whileHover={{ scale: 1.1 }}
                className="btn glass text-white">
                <a href='https://charlees-heat-at-home.square.site/' target='_blank'>Order Now</a>
              </motion.button>
            </div>
          </div>
        </div>
        <div className='container mx-auto py-24'>
          <Menu menu={menu} />
        </div>
      </main>
      <Footer />
    </div>
  )
}

export async function getServerSideProps({ preview = true }) {
  const headers = (await getHeaders(preview)) ?? []
  const logo = (await getLogo(preview)) ?? []
  const menu = (await getMenu(preview)) ?? []
  const background = (await getBackground(preview)) ?? []

  return {
    props: { headers, logo, menu, background },
  }
}
