import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getHeaders, getLogo } from '../lib/api'

export default function Home(props) {
  console.log(props)

  const headers = props.headers.data.headersCollection.items
  const logo = props.logo.data.logo
  console.log(headers[0].firstHeader)
  return (
    <div className={styles.description}>
      <Head>
        <title>Charlees at home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <img src={logo.image.url} alt={logo.title} />
        <h1 className={styles.title}>
          {headers[0].firstHeader}
        </h1>
        <h3 className={styles.description}>
          {headers[0].description}
        </h3>
      </main>
    </div>
  )
}

export async function getServerSideProps({ preview = true }) {
  const headers = (await getHeaders(preview)) ?? []
  const logo = (await getLogo(preview)) ?? []

  return {
    props: { headers, logo },
  }
}
